# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs_recurring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringcost',
            name='total_billing_cycles',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Stop billing after this many billing cycles', null=True),
        ),
    ]
