# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0003_check_zero_amount_20160907_0921'),
        ('costs_recurring', '0002_recurringcost_total_billing_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringcost',
            name='total_billing_cycles',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Stop billing after this many billing cycles. Leave blank to have this cost continually recur.', null=True),
        ),
        migrations.AlterField(
            model_name='recurringcostsplit',
            name='portion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=13),
        ),
        migrations.AlterUniqueTogether(
            name='recurringcostsplit',
            unique_together=set([('recurring_cost', 'from_account')]),
        ),
    ]
