# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20160924_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionimportcolumn',
            options={'ordering': ['transaction_import', 'column_number']},
        ),
        migrations.AddField(
            model_name='transactionimportcolumn',
            name='example',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionimport',
            name='has_headings',
            field=models.BooleanField(default=True, verbose_name='First line of file contains headings'),
        ),
        migrations.AlterField(
            model_name='transactionimportcolumn',
            name='column_heading',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Column'),
        ),
        migrations.AlterField(
            model_name='transactionimportcolumn',
            name='to_field',
            field=models.CharField(blank=True, choices=[('', 'None'), ('date', 'Date'), ('amount', 'Amount'), ('amount_out', 'Amount (money in only)'), ('amount_in', 'Amount (money out only)'), ('description', 'Description / Notes')], default='', max_length=20, verbose_name='Is'),
        ),
        migrations.AlterField(
            model_name='transactionimportcolumn',
            name='transaction_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='transactions.TransactionImport'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionimportcolumn',
            unique_together=set([('transaction_import', 'to_field'), ('transaction_import', 'column_number')]),
        ),
    ]
