# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160924_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionimportcolumn',
            name='to_field',
            field=models.CharField(blank=True, choices=[('', 'None'), ('date', 'Date'), ('amount', 'Amount'), ('amount_out', 'Amount (money in only)'), ('amount_in', 'Amount (money out only)'), ('description', 'Description / Notes')], default=None, max_length=20, null=True, verbose_name='Is'),
        ),
    ]
