# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160924_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionimportcolumn',
            name='format',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionimportcolumn',
            name='example',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionimportcolumn',
            name='to_field',
            field=models.CharField(blank=True, choices=[('', '-'), ('date', 'Date'), ('amount', 'Amount'), ('amount_out', 'Amount (money in only)'), ('amount_in', 'Amount (money out only)'), ('description', 'Description / Notes')], default=None, max_length=20, null=True, verbose_name='Is'),
        ),
    ]
