# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20160925_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionimportcolumn',
            name='format',
        ),
        migrations.AddField(
            model_name='transactionimport',
            name='date_format',
            field=models.CharField(choices=[('%d-%m-%Y', 'dd-MM-yyyy'), ('%d/%m/%Y', 'dd/MM/yyyy'), ('%d.%m.%Y', 'dd.MM.yyyy'), ('%d-%Y-%m', 'dd-yyyy-MM'), ('%d/%Y/%m', 'dd/yyyy/MM'), ('%d.%Y.%m', 'dd.yyyy.MM'), ('%m-%d-%Y', 'MM-dd-yyyy'), ('%m/%d/%Y', 'MM/dd/yyyy'), ('%m.%d.%Y', 'MM.dd.yyyy'), ('%m-%Y-%d', 'MM-yyyy-dd'), ('%m/%Y/%d', 'MM/yyyy/dd'), ('%m.%Y.%d', 'MM.yyyy.dd'), ('%Y-%d-%m', 'yyyy-dd-MM'), ('%Y/%d/%m', 'yyyy/dd/MM'), ('%Y.%d.%m', 'yyyy.dd.MM'), ('%Y-%m-%d', 'yyyy-MM-dd'), ('%Y/%m/%d', 'yyyy/MM/dd'), ('%Y.%m.%d', 'yyyy.MM.dd'), ('%d-%m-%y', 'dd-MM-yy'), ('%d/%m/%y', 'dd/MM/yy'), ('%d.%m.%y', 'dd.MM.yy'), ('%d-%y-%m', 'dd-yy-MM'), ('%d/%y/%m', 'dd/yy/MM'), ('%d.%y.%m', 'dd.yy.MM'), ('%m-%d-%y', 'MM-dd-yy'), ('%m/%d/%y', 'MM/dd/yy'), ('%m.%d.%y', 'MM.dd.yy'), ('%m-%y-%d', 'MM-yy-dd'), ('%m/%y/%d', 'MM/yy/dd'), ('%m.%y.%d', 'MM.yy.dd'), ('%y-%d-%m', 'yy-dd-MM'), ('%y/%d/%m', 'yy/dd/MM'), ('%y.%d.%m', 'yy.dd.MM'), ('%y-%m-%d', 'yy-MM-dd'), ('%y/%m/%d', 'yy/MM/dd'), ('%y.%m.%d', 'yy.MM.dd')], default='%d-%m-%Y', max_length=50),
        ),
    ]
