# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housemate', to=settings.AUTH_USER_MODEL),
        ),
    ]
