# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_auto_20161008_1841'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE costs_recurringcost ADD CONSTRAINT one_off_costs_must_be_type_normal
            CHECK ("type" = 'normal' OR total_billing_cycles IS NULL)
            """,
            "ALTER TABLE costs_recurringcost DROP CONSTRAINT one_off_costs_must_be_type_normal"
        )
    ]
