# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_check_one_off_must_be_type_normal'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE costs_recurringcost ADD CONSTRAINT check_total_billing_cycles_over_zero
            CHECK (total_billing_cycles IS NULL or total_billing_cycles > 0)
            """,
            "ALTER TABLE costs_recurringcost DROP CONSTRAINT check_total_billing_cycles_over_zero"
        )
    ]
