# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_cycle', '0004_auto_20161001_1707'),
        ('costs', '0005_check_recurring_costs_have_splits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringcostsplit',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='recurringcost',
            name='initial_billing_cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing_cycle.BillingCycle'),
            preserve_default=False,
        ),
    ]
