# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_check_disabled_xor_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringcost',
            name='initial_billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_cycle.BillingCycle'),
        ),
    ]
