# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0011_check_fixed_amount_requires_type_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurredcost',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurred_cost', to='hordak.Transaction'),
        ),
    ]
