# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0012_auto_20171129_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringcost',
            name='type',
            field=models.CharField(choices=[('normal', "We will not have spent this yet. We will estimate a fixed amount per billing cycle. (You should select a 'liabilities' account)."), ('arrears_balance', "We will have already spent this in the previous billing cycle, so bill the account's balance. (You should select an 'expenses' account)"), ('arrears_transactions', "We will have already spent this in the previous cycle, so bill the total amount spent in the previous cycle. (You should select an 'expenses' account)")], default='normal', max_length=20),
        ),
    ]
