# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0015_auto_20171206_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurredcost',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurred_cost', to='hordak.Transaction'),
        ),
    ]
