# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, unique=True)),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField(help_text='The start and end date of this billing cycle. May not overlay with any other billing cycles.')),
                ('transactions_created', models.BooleanField(default=False, help_text='Have transactions been created for this billing cycle?')),
            ],
        ),
    ]
