# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_cycle', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE billing_cycle_billingcycle ADD CONSTRAINT non_overlapping_billing_cycles
            EXCLUDE USING GIST (date_range WITH &&)
            """,
            "ALTER TABLE billing_cycle_billingcycle DROP CONSTRAINT non_overlapping_billing_cycles"
        )
    ]
