# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_cycle', '0003_check_adjacent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingcycle',
            options={'ordering': ['date_range']},
        ),
    ]
