# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_cycle', '0005_auto_20171203_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='statements_sent',
            field=models.BooleanField(default=False, help_text='Have we sent housemates their statements for this billing cycle?'),
        ),
    ]
