# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171203_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='payment_information',
            field=models.TextField(blank=True, default='', help_text='Enter information on how payment should be made, such as the bank account details housemates should pay into.'),
        ),
    ]
