# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tellerio_enable',
            field=models.BooleanField(default=False, help_text='Enable daily imports from teller.io'),
        ),
    ]
