# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_tellerio_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='tellerio_enable',
            field=models.BooleanField(default=False, verbose_name='Enable daily teller.io imports'),
        ),
    ]
