# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20171207_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
